const booking="https://waterfront_retreat_direct_booking.guestybookings.com/en";
const bookingAttrs='target="_blank" rel="noopener noreferrer"';
const amenities=[
["◌","Comfort",["Air conditioning","Heating","Private hot tub","Hot water","Wi-Fi","TV","Bed linens","Hair dryer"]],
["⌂","Kitchen & Dining",["Keurig coffee maker","Coffee","Kitchenette","Mini fridge","Toaster","Cooking basics","Dishes & silverware","Wine glasses","BBQ grill & utensils"]],
["≈","Outdoor & Lake",["Waterfront","Lake access","Kayaks","Fire pit","Outdoor shower","Outdoor dining","Outdoor furniture","Private patio or balcony"]],
["✓","Safety & Essentials",["Private entrance","Private living room","Free parking","Single-level home","Smoke alarm","Carbon monoxide alarm","Fire extinguisher","First aid kit","Board games","Bath essentials"]]
];
const cabins={
"blue-heron":{number:"01",name:"Blue Heron Cabin",card:"images/blue-heron.webp",hero:"images/blue-heron.webp",tagline:"Romantic • Peaceful • Lakeside Adventure",intro:"A warm, intimate lakeside escape for two",copy:"Blue Heron Cabin sits quietly along Pickwick Lake, offering a warm, intimate escape for couples who want both relaxation and a touch of adventure. Mornings begin with soft light over the water, and days can be spent exploring the shoreline, wandering through nature, or simply enjoying the calm from your private porch.",highlight:"Private hot tub and outdoor shower",gallery:["images/blue-heron.webp"]},
"eagles-nest":{number:"02",name:"Eagle’s Nest",card:"images/eagles-nest.webp",hero:"images/eagles-nest.webp",tagline:"Adventurous • Elevated • Scenic",intro:"Your private lookout above the treetops",copy:"Perched above the treetops, Eagle’s Nest is designed for couples who love a mix of adventure and quiet connection. Wake up to wide lake views, spend the day exploring the water or nearby trails, and return to a cabin that feels like your own private lookout.",highlight:"Elevated deck with peaceful lake views",gallery:["images/eagles-nest.webp"]},
"butterfly-bungalow":{number:"03",name:"Butterfly Bungalow",card:"images/butterfly-bungalow.webp",hero:"images/butterfly-bungalow.webp",tagline:"Romantic • Cozy • Whimsical",intro:"A whimsical hideaway filled with warmth",copy:"Soft, colorful, and full of charm, the Butterfly Bungalow is your intimate hideaway on Pickwick Lake. Designed for couples who crave connection and quiet moments, this cozy cabin wraps you in warmth from the moment you step inside. Enjoy slow mornings with coffee on the porch and peaceful evenings under the string lights.",highlight:"King bed, electric fireplace, and private hot tub",gallery:["images/butterfly-bungalow.webp"]}
};
const home=document.querySelector("#home-cabins");
if(home)home.innerHTML=Object.entries(cabins).map(([slug,c])=>`<article><div class="photo"><img src="${c.card}" alt="${c.name}"></div><div class="card-copy"><p class="feature">${c.tagline}</p><h3>${c.name}</h3><p>${c.copy}</p><div class="meta"><span>1 bedroom</span><span>1 bath</span><span>2 guests</span></div><div class="card-actions"><a href="cabin.html?c=${slug}">Explore cabin →</a><a href="${booking}" ${bookingAttrs}>Book</a></div></div></article>`).join("");
const chooser=document.querySelector("#chooser-grid");
if(chooser)chooser.innerHTML=Object.entries(cabins).map(([slug,c])=>`<a class="chooser-card" href="cabin.html?c=${slug}"><img src="${c.card}" alt="${c.name}"><div class="chooser-shade"></div><span class="chooser-number">${c.number}</span><div class="chooser-copy"><p>${c.tagline}</p><h2>${c.name}</h2><span>${c.intro}</span><strong>Explore this cabin →</strong></div></a>`).join("");
const lake=document.querySelector("#lake-gallery");
if(lake){lake.innerHTML=`<figure class="lake-life-feature"><img src="images/firepit.webp" alt="Life at Pickwick Lake" loading="lazy"><figcaption>Life at Pickwick Lake</figcaption></figure>`}
const page=document.querySelector("#cabin-page");
if(page){const key=new URLSearchParams(location.search).get("c")||"blue-heron",c=cabins[key]||cabins["blue-heron"];document.title=`${c.name} | Waterfront Retreat`;page.innerHTML=`
<header class="detail-header"><a class="brand" href="./"><b>Waterfront Retreat</b><span>on Pickwick Lake</span></a><nav><a href="cabins.html">All cabins</a><a href="./#contact">Contact</a><a class="nav-book" href="${booking}" ${bookingAttrs}>Book now</a></nav></header>
<section class="detail-hero"><img src="${c.hero}" alt="${c.name}"><div class="overlay"></div><div class="detail-title"><p class="kicker light">${c.tagline}</p><h1>${c.name}</h1><p>${c.intro}</p></div></section>
<section class="detail-intro"><div><p class="kicker">Your private retreat</p><h2>${c.intro}</h2><p>${c.copy}</p><a class="btn gold" href="${booking}" ${bookingAttrs}>Check dates & book</a></div><aside><span>Cabin highlight</span><strong>${c.highlight}</strong><div class="detail-meta"><span>1 bedroom</span><span>1 bathroom</span><span>2 adults</span></div></aside></section>
<section class="cabin-gallery"><div class="gallery-heading"><div><p class="kicker">Step inside</p><h2>Explore ${c.name}</h2></div><p>Take a closer look at your private cabin and peaceful outdoor spaces.</p></div><div class="gallery-grid">${c.gallery.map((src,i)=>`<figure class="${i===0||i===4?"gallery-feature":""}"><img src="${src}" alt="${c.name}" loading="lazy"></figure>`).join("")}</div></section>
<section class="amenities amenity-groups"><p class="kicker">Everything you need</p><h2>Cabin amenities</h2><p class="amenity-intro">Select a category to see what is included.</p><div class="amenity-accordion">${amenities.map(g=>`<details class="amenity-drop"><summary><span class="amenity-drop-icon">${g[0]}</span><strong>${g[1]}</strong><span class="amenity-count">${g[2].length} amenities</span><span class="amenity-chevron">⌄</span></summary><ul>${g[2].map(x=>`<li>${x}</li>`).join("")}</ul></details>`).join("")}</div></section>
<section class="detail-cta"><p class="kicker light">Pickwick Lake is calling</p><h2>Make ${c.name} yours.</h2><p>View live availability and reserve securely through Guesty.</p><div class="actions"><a class="btn gold" href="${booking}" ${bookingAttrs}>Book ${c.name}</a><a class="btn clear" href="cabins.html">Explore other cabins</a></div></section>
<footer><div class="brand"><b>Waterfront Retreat</b><span>on Pickwick Lake</span></div><p>Private waterfront cabins for couples in Cherokee, Alabama.</p><div class="links"><a href="tel:+12563351827">256-335-1827</a><a href="mailto:info@waterfrontretreatonpickwicklake.com">info@waterfrontretreatonpickwicklake.com</a></div><small>© 2026 Waterfront Retreat on Pickwick Lake</small></footer>`}
